### ISSUE TITLE
WP-CLI re-index command misbehaves when SiteOrigin Page Builder is used on site

### ISSUE THREAD

**Issue by KZeni** [WebDevStudios/wp-search-with-algolia#9] opened 2019-08-27 18:15 UTC
I have a site using SiteOrigin Page Builder (https://wordpress.org/plugins/siteorigin-panels/) on some pages and not others.

It appears that re-indexing the site using the buttons provided in the site admin work fine. **_However_**, running `wp algolia reindex –all` for that same exact site has it so the last item with Page Builder being used has its content used for any/all non-Page Builder items after that (even though those items have their own content, excerpts, etc.)

I’m wondering if it’s the fact that `ob_start()` and `ob_end_clean()` are being used for the non-CLI reindex functionality whereas it isn’t for the CLI command, and the use of SiteOrigin Page Builder needs those two functions to be used to prevent the issues during indexing I mentioned.

I will simply opt to use the non-CLI reindex option for now, but it would be ideal if both options were to be available & problem-free.

Btw, this was posted on https://wordpress.org/support/topic/wp-cli-re-index-command-misbehaves-when-siteorigin-page-builder-is-used-on-site-2/ where it was suggested to post about it here. Even then, this request originates from https://wordpress.org/support/topic/wp-cli-re-index-command-misbehaves-when-siteorigin-page-builder-is-used-on-site/, but I figured it could be mentioned here since it’s still something worth addressing.

**Comment by richaber** [comment] 2019-08-31 01:49
Howdy @KZeni,

I am sorry to hear you have this issue.
However, I am unable to reproduce the issue as described.

Here are the steps I took, to attempt to reproduce:

1. Spun up a new local environment
1. PHP 5.6
1. MySQL 5.6
1. NGINX 1.10.1
1. WordPress 5.2.2
1. WP-CLI 2.3.0
1. Imported WPTRT theme unit test data
1. Installed Page Builder by SiteOrigin 2.10.10
1. Installed SiteOrigin Widgets Bundle 1.15.8
1. Created a few pages using SiteOrigin's Pre-Built Layouts
1. Created a few additional pages with Classic Editor
1. Set up a fresh index in Algolia
1. Installed WP Search with Algolia 1.0.0
1. Configured WP Search with Algolia API keys
1. Enabled autocomplete
1. Enabled Pages, Posts, Tags, and Categories indices for autocomplete
1. Set Search Page settings to `Use Algolia in the backend`
1. Ran `$ wp algolia reindex --all` on the command line
1. Checked the index results in Algolia's own dashboard
1. The content of Page Builder pages were not duplicated into Classic Editor pages
1. Tested search on the front end of the WP site
1. Autocomplete appeared to behave as expected
1. Search results appeared to behave as expected
1. Returned to plugin settings
1. Set Search Page settings to `Use Algolia with Instantsearch.js`
1. Ran `$ wp algolia reindex --all` on the command line
1. Checked the index results in Algolia dashboard
1. The content of Page Builder pages were not duplicated into Classic Editor pages
1. Tested search on the front end of the WP site
1. Autocomplete appeared to behave as expected
1. Search results appeared to behave as expected

Since I can't seem to reproduce this on a fairly stock install, it is possible that there is some third-party code, in a theme, plugin, or cli package, that could be triggering the issue you are describing.

You could try passing the `--debug` argument to the WP-CLI command when you reindex, and that *might* provide some useful insight into debugging your issue, if there are any PHP warnings or errors produced that you wouldn't normally see:

```
$ wp algolia reindex --all --debug
```

I am closing this issue, due to an inability to reproduce.
It does not appear to be a bug in the WP Search with Algolia plugin, but possibly an issue in a third-party component.

**Comment by KZeni** [comment] 2019-09-04 17:59
Okay, it appears to have been caused by shortcodes within the theme using `ob_start();` and `return ob_get_clean();` to pull & return the data accordingly. However, I still had content within search results displaying that shortcode content even though it wasn't found anywhere within that search results content.

I'm thinking `wp algolia reindex` has an issue when shortcodes use `ob_start();` and `return ob_get_clean();` without additional precautions/refinements taken into account. Again, this isn't an issue whatsoever when using the "Re-index search page records" button found in the site admin. **_As such, I'm thinking this is something that should still be addressed_** (why does the WP-CLI reindex command have an issue with these conditions/use-case while the site admin button doesn't... and why would it then be okay for WP-CLI to still have that issue?)

As an immediate fix to get WP-CLI reindexing working for my specific site, I made sure to check all shortcodes using `ob_start` so they first check & match the post type being used via `get_post_type()` and only have it execute when on the post type that's expected for the shortcode to be used in (then using `return '';` if the post type didn't match what was expected.) This then prevents shortcodes from triggering ob_start when they shouldn't be, but I'm thinking that whatever's allowing the web-based reindex command to not have an issue with this should also be done for the WP-CLI reindex command so this type of workaround isn't needed by website managers/theme creators/etc.

**Comment by richaber** [comment] 2019-09-06 22:08
@KZeni are the shortcodes you reference provided by a plugin or theme that I can install to test against?

**Comment by KZeni** [comment] 2019-09-11 19:30
They were part of the theme I was given to work with.

Here's an example of what was problematic as a shortcode for Algolia's re-indexing via WP-CLI and Page Builder (though Page Builder might not necessarily be involved in what's causing this): https://gist.github.com/KZeni/3c655e5cdb1ffc6da441727b022b5425/b71fe504d5ce9f56a412c6bfb209c7b37fa02d03

You can then see what was done to prevent this here: https://gist.github.com/KZeni/3c655e5cdb1ffc6da441727b022b5425/19e990f5e91a18a45b4a4cc90569796bff2b5cb1 (with the differences shown here: https://gist.github.com/KZeni/3c655e5cdb1ffc6da441727b022b5425/revisions) Again, I really just made it so shortcodes were isolated to the post types they're used on so things that are being indexed don't then have their search preview/excerpt be populated with the output of these shortcodes (even though the shortcodes aren't actually used on that search result whatsoever & not even for that post type as a whole).

**Comment by richaber** [comment] 2019-10-04 18:13
I'm sorry @KZeni, I still can't reproduce the issue.

I made a small plugin to load the "problematic shortcode" (not the version that was changed to prevent the issue) into my test environment, added the shortcode to a couple of pages, some with the Siteorigin Page Builder, some without, and a couple of posts, and ran the WP-Cli command `wp algolia reindex --all`.

I do not see duplicate data in my Algolia index, autocomplete, or search results.

I do not have all the same plugins/theme/data you have, so this isn't exactly a 100% accurate test, but as far as I can see, it didn't trigger any issues with using the WP-CLi reindex command.

**Comment by KZeni** [comment] 2019-10-04 18:28
Okay. Thanks for looking into it!

I was hoping it would be a matter of looking into the process of the WP-CLI reindex vs. the site admin's re-index button with the cause being somewhat clear given the description (and potentially being able to recreate it). I understand if you want to leave this be given the circumstances.

At this point, I found a solution to the issue for my own needs so we can probably just have this out there as a reference & potentially revisit it again if it comes up again.

Thanks again,
Kurt

**Closed** 2019-10-05 20:47 UTC
