### ISSUE TITLE
Restrict Domain

### ISSUE THREAD

**Issue by SimeonGriggs** [WebDevStudios/wp-search-with-algolia#28] opened 2019-11-13 15:44 UTC
We use Development and Staging domains and have run into instances where these are added to the index. I'm wary of testing this plugin without the ability to deactivate indexing depending on the domain.

I'd like a Filter to be able to say `if (home_url() !=== http://example.com) { return false }`

**Comment by richaber** [comment] 2019-11-15 23:34
Have you considered using different index prefixes per environment?
For example `DEVwp_` for dev and `STGwp_` for stage?

**Comment by SimeonGriggs** [comment] 2019-11-15 23:36
Kinda doesn’t solve the issue. This site has 50k+ records and I’m trying to avoid indexing them multiple times...

**Comment by richaber** [comment] 2019-11-29 15:56
Howdy @SimeonGriggs, if I understand correctly, the issue is that you do not want to index when you are developing locally (or in an environment _other than production_).

I think you could accomplish that by writing a little plugin of your own, utilizing the existing "should index" filters, `algolia_should_index_searchable_post`, `algolia_should_index_post`, `algolia_should_index_term`, and `algolia_should_index_user`.

Here's a really oversimplified example you could test with.

```
/**
 * Determine if we should allow indexing.
 *
 * @param bool $should_index Whether to index or not.
 *
 * @return bool
 */
function myprefix_algolia_should_index( $should_index ) {

	// Whatever logic you want to use to determine whether to index or not.
	if ( home_url() !== 'http://example.com' ) {
		return false;
	}

	return $should_index;
}

add_filter( 'algolia_should_index_searchable_post', 'myprefix_algolia_should_index' );
add_filter( 'algolia_should_index_post', 'myprefix_algolia_should_index' );
add_filter( 'algolia_should_index_term', 'myprefix_algolia_should_index' );
add_filter( 'algolia_should_index_user', 'myprefix_algolia_should_index' );
```

**Comment by SimeonGriggs** [comment] 2019-11-29 18:04
Oooh that's terrific. Thank you.

**Comment by richaber** [comment] 2019-11-29 18:27
@SimeonGriggs You are welcome. Please let us know if that does indeed solve the issue for you.

**Comment by richaber** [comment] 2019-12-07 02:26
@SimeonGriggs I'm closing this ticket, under the assumption that snippet helped lead you to a solution.

**Closed by richaber** 2019-12-07 02:26 UTC
Labels: enhancement, question

**Comment by thomasmb** [comment] 2021-12-03 12:21
Hi, I was looking into this just now. With the snippet above, it would actually delete the item from the index if the record already existed.
