### ISSUE TITLE
wp algolia reindex --all index disabled index also

### ISSUE THREAD

**Issue by yogeshbeniwal** [WebDevStudios/wp-search-with-algolia#290] opened 2023-01-18 01:54 UTC
**Describe the bug**
wp algolia reindex --all, reindex disabled index searchable_posts also

**To Reproduce**
1. Disable searchable_posts index in settings and enable other required indexes
2. Run `wp algolia reindex --all` to reindex 
3. Observe searchable_posts is also reindex 

**Expected behavior**
searchable_posts index should not be included in reindexing while disabled

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/7325107/213061965-fb6003be-f263-41cd-8217-2ff91582a31d.png)

**Comment by yogeshbeniwal** [comment] 2023-01-18 03:08
This is happening because `Use Algolia with Instantsearch.js` options use the searchable_posts index for the Search Page feature. Ideally search page also should show results from selected index only. Otherwise it will show other custom post types and users, which is unnecessary.

**Comment by yogeshbeniwal** [comment] 2023-01-18 16:37
> The issue here is that the searchable_posts index is considered enabled.

Is there a way searchable_posts can be stopped being indexed?

**Comment by tw2113** [comment] 2023-01-18 16:40
You'd have to turn it off in the Search page settings before running a bulk index via WP-CLI, and then turn it back on again after you're done.

For what it's worth the Search Page settings are a separate index from the ones created for Autocomplete, and that was by design from Algolia before we forked the plugin.

**Comment by ramsesdelr** [comment] 2023-07-04 21:12
Should this be considered for further discussion or can we create a flag to exclude the **searchable_posts** when this happens?

**Comment by tw2113** [comment] 2023-07-05 13:45
I see no reason to close it yet, so feel free to continue discussion.

**Comment by tw2113** [comment] 2023-07-27 16:54
Adding some context after trying some things out myself.

If you have both "Search results" set to "Do not use Algolia" and you do not have "All Posts" checked in the Autocomplete settings, then running `wp algolia reindex --all` should NOT be running with `wp_searchable_posts`.

This would because "All Posts" is a slightly special Autocomplete usecase which re-uses the `wp_searchable_posts` index as a general catchall for Autocomplete.

With that said, I don't think there's any issue or bug to really fix here, as behavior is as expected based on chosen settings. If you don't want wp-cli to be including the searchable posts index, make sure your search results aren't enabled, and Autocomplete doesn't include "All Posts".

**Comment by abdulkadernsu** [comment] 2023-09-23 13:11
I have 250k + product on my woocommerce site. I have implemented wp search with algolia for searching. The fact is it is taking too much time to get indexing. I have counted only "100 data get indexed in 30 sec around". How can I do fast indexing? Also if I update my products in future, how it will sync with algolia without reindexing again?
Thanks

**Comment by tw2113** [comment] 2023-09-23 17:32
@abdulkadernsu Responded in your own issue, as yours doesn't apply to this present issue at hand.

**Comment by tw2113** [comment] 2023-10-24 14:27
Closing this one as I don't think there's an issue that needs fixed at this time. Based on my previous findings, things run like expected.

**Closed by tw2113** 2023-10-24 14:27 UTC
